import { MANIPULATION_OPERATIONS } from '../../exercises/manipulateSyllablesConfig.js';
import { updateSessionProgress } from '../session/sessionProgress.js';
import { renderCommonMetrics } from '../session/sessionSummary.js';
import { clearProfessionalControls, renderProfessionalControls } from '../session/professionalControls.js';

export const MANIPULATE_SYLLABLES_ACTIVITY_ID = 'manipulate-syllables';
const labels=Object.fromEntries(Object.values(MANIPULATION_OPERATIONS).map(item=>[item.id,item.label]));
const template=`<section id="manip-config" class="screen" aria-labelledby="manip-config-title"><button class="back-link" data-runtime-home type="button">← Volver al inicio</button><p class="brand">LEXIA</p><h1 id="manip-config-title" tabindex="-1">Configura Manipular sílabas</h1><form data-config class="session-config"></form></section>
<section id="manip-game" class="screen game" aria-labelledby="manip-game-title"><header class="game-header"><div><p data-round></p><p data-score>Al primer intento: 0</p></div><button data-exit class="secondary" type="button">Salir de la actividad</button></header><div data-progress class="progress" role="progressbar" aria-label="Progreso de la sesión"><span></span></div><div data-professional class="professional-bar hidden" aria-label="Controles profesionales"></div><div class="play-card" aria-describedby="manip-instruction"><p data-operation class="brand"></p><h1 id="manip-game-title" tabindex="-1">Transforma la palabra</h1><p class="base-word">Palabra: <strong data-base></strong></p><p id="manip-instruction" data-instruction class="instruction" tabindex="-1"></p><button data-help-toggle class="help-toggle" type="button" aria-expanded="false" aria-controls="manip-helper">¿Cómo se hace?</button><p id="manip-helper" data-helper class="manip-helper hidden"></p><div data-extra-zone class="extra-zone hidden"><p data-extra-label class="zone-label"></p><div data-extra class="pieces"></div></div><div data-workspace class="manip-workspace" aria-label="Palabra construida"></div><div class="edit-controls"><button data-undo class="secondary" type="button">↶ Deshacer</button><button data-reset class="secondary" type="button">Reiniciar</button></div><p data-announcement class="sr-only" aria-live="polite"></p><p data-feedback class="feedback" aria-live="polite"></p><p data-revealed class="revealed" aria-live="polite"></p><button data-check class="primary wide" type="button">Comprobar respuesta</button><button data-next class="primary wide hidden" type="button">Siguiente ronda</button><button data-empty-back class="secondary wide hidden" type="button">Volver a la configuración</button></div></section>
<section id="manip-summary" class="screen" aria-labelledby="manip-summary-title"><p class="brand">SESIÓN COMPLETADA</p><h1 id="manip-summary-title" tabindex="-1">Resumen de Manipular sílabas</h1><div data-metrics class="metrics"></div><h2>Resultados por operación</h2><div data-groups class="operation-summary"></div><h2>Interacción durante la sesión</h2><div data-interaction class="interaction-summary"></div><h2>Retos trabajados</h2><ul data-results class="results"></ul><div class="summary-actions"><button data-repeat class="primary" type="button">Repetir configuración</button><button class="secondary" data-runtime-home type="button">Volver al inicio</button></div></section>`;
const pieceButton=(piece,action,selected,disabled)=>`<button class="piece manip-piece${selected?' selected':''}" type="button" draggable="${!disabled}" data-action="${action}" data-piece="${piece.id}"${action.includes('select')?` aria-pressed="${selected}"`:''}${disabled?' disabled':''}>${piece.text}${selected?'<span class="selection-mark" aria-hidden="true">✓</span>':''}</button>`;
const insertionLabel=(index,pieces)=>index===0?'Insertar al principio':index===pieces.length?'Insertar al final':`Insertar después de ${pieces[index-1].text.toLocaleUpperCase('es')}`;

export function createManipulateSyllablesController({plugin,root,shell,dialogs,createConfigurator}){
 let host,refs,configurator,events,result,dragged;
 const q=selector=>host.querySelector(selector);
 function mount(){if(host)return;host=document.createElement('div');host.dataset.activityRoot=MANIPULATE_SYLLABLES_ACTIVITY_ID;host.innerHTML=template;root.append(host);refs={form:q('[data-config]'),workspace:q('[data-workspace]'),extraZone:q('[data-extra-zone]'),extra:q('[data-extra]'),extraLabel:q('[data-extra-label]'),helper:q('[data-helper]'),help:q('[data-help-toggle]'),announcement:q('[data-announcement]'),feedback:q('[data-feedback]'),check:q('[data-check]'),next:q('[data-next]'),undo:q('[data-undo]'),reset:q('[data-reset]'),progress:q('[data-progress]'),professional:q('[data-professional]')};configurator=createConfigurator(refs.form,MANIPULATE_SYLLABLES_ACTIVITY_ID);events=new AbortController();const o={signal:events.signal};refs.form.addEventListener('submit',e=>{e.preventDefault();startSession();},o);host.addEventListener('click',handleClick,o);host.addEventListener('dragstart',handleDragStart,o);refs.workspace.addEventListener('dragover',e=>e.preventDefault(),o);refs.workspace.addEventListener('drop',handleDrop,o);}
 function openConfiguration(){shell.show('manip-config');}
 function startSession(){const config=configurator.getConfig();const started=plugin.start(config);if(started.status==='insufficient'){configurator.setStartError('No se puede iniciar: faltan retos únicos para completar la distribución equilibrada por operación. Revisa la disponibilidad.');return;}configureProfessional();shell.show('manip-game');renderRound(started);}
 function handleClick(event){if(event.target.closest('[data-runtime-home]')){destroy();shell.home();return;}if(event.target.closest('[data-exit]')){dialogs.exit.open();return;}if(event.target.closest('[data-repeat],[data-empty-back]'))return openConfiguration();if(event.target.closest('[data-help-toggle]')){const expanded=refs.help.getAttribute('aria-expanded')==='true';refs.help.setAttribute('aria-expanded',String(!expanded));refs.helper.classList.toggle('hidden',expanded);return;}const button=event.target.closest('[data-action]');if(button&&button.dataset.action!=='none')return act(button);if(event.target.closest('[data-undo]'))update(plugin.submit({type:'undo'}));if(event.target.closest('[data-reset]'))update(plugin.submit({type:'reset'}));if(event.target.closest('[data-check]')){const next=plugin.submit({type:'validate'});update(next);requestAnimationFrame(()=>(next.status==='correct'?refs.next:refs.undo.disabled?refs.reset:refs.undo).focus());}if(event.target.closest('[data-next]')){const next=plugin.next();if(next.status==='complete')finishSession();else renderRound(next);}}
 function act(button){const action={type:button.dataset.action};if(button.dataset.piece)action.pieceId=button.dataset.piece;if(button.dataset.slot!==undefined)action.slotIndex=Number(button.dataset.slot);const next=plugin.submit(action);update(next);requestAnimationFrame(()=>{const selected=host.querySelector(`[data-piece="${next.selectedPieceId}"]`);(selected||(next.canValidate?refs.check:refs.workspace.querySelector('button:not(:disabled)'))||refs.undo).focus();});}
 function handleDragStart(event){const piece=event.target.closest('[data-piece]');if(!piece)return;dragged=piece.dataset.piece;if(refs.extra.contains(piece))update(plugin.submit({type:'select-extra',pieceId:dragged}));else if(result.operation==='invert')update(plugin.submit({type:'select-swap-piece',pieceId:dragged}));}
 function handleDrop(event){event.preventDefault();const slot=event.target.closest('[data-slot]'),piece=event.target.closest('[data-piece]');if(slot&&dragged)update(plugin.submit({type:'insert-at',slotIndex:Number(slot.dataset.slot)}));else if(piece&&dragged)update(plugin.submit({type:result.operation==='replace'?'replace-piece':'select-swap-piece',pieceId:piece.dataset.piece}));dragged=null;}
 function renderWorkspace(next){const selected=next.selectedPieceId;if(next.operation==='add'&&next.extraAvailable){refs.workspace.innerHTML=next.currentPieces.map((piece,index)=>`<button class="insert-slot" type="button" data-action="insert-at" data-slot="${index}" aria-label="${insertionLabel(index,next.currentPieces)}"${selected?'':' disabled'}>+</button>${pieceButton(piece,'none',false,true)}`).join('')+`<button class="insert-slot" type="button" data-action="insert-at" data-slot="${next.currentPieces.length}" aria-label="${insertionLabel(next.currentPieces.length,next.currentPieces)}"${selected?'':' disabled'}>+</button>`;return;}const action=next.operation==='remove'?'remove-piece':next.operation==='replace'?'replace-piece':next.operation==='invert'?'select-swap-piece':'none';const locked=next.roundCompleted||(next.operation==='remove'&&next.historyLength>0)||(next.operation==='replace'&&!selected);refs.workspace.innerHTML=next.currentPieces.map(piece=>pieceButton(piece,action,selected===piece.id,locked||action==='none')).join('');}
 function update(next){result=next;renderWorkspace(next);const hasExtra=['add','replace'].includes(next.operation);refs.extraZone.classList.toggle('hidden',!hasExtra);refs.extraLabel.textContent=next.operation==='add'?'Ficha para añadir':'Ficha nueva';refs.extra.innerHTML=hasExtra&&next.extraAvailable?pieceButton(next.extraPiece,'select-extra',next.selectedPieceId===next.extraPiece.id,next.roundCompleted):'';refs.undo.disabled=!next.historyLength||next.roundCompleted;refs.reset.disabled=next.roundCompleted||!next.isModified;refs.check.disabled=!next.canValidate;refs.announcement.textContent=next.announcement;if(!['incorrect','correct'].includes(next.status)){refs.feedback.textContent='';refs.feedback.className='feedback';}if(next.status==='incorrect'){const guidance={remove:'Comprueba cuál es la sílaba indicada y deja las demás en su orden.',add:'Revisa primero la ficha nueva y después el lugar que indica la consigna.',replace:'Comprueba qué ficha debe salir y conserva las demás en su sitio.',invert:'Compara las posiciones iniciales y decide qué dos fichas aún debes intercambiar.'};refs.feedback.textContent=configurator.getPolicy().explicitFeedback?guidance[next.operation]:'El resultado no es correcto. Revisa la consigna e inténtalo de nuevo.';refs.feedback.className='feedback error';}if(next.status==='correct'){refs.feedback.textContent='¡Muy bien! Has transformado correctamente la palabra.';refs.feedback.className='feedback success';q('[data-revealed]').textContent=next.expectedText;refs.check.classList.add('hidden');refs.next.classList.remove('hidden');q('[data-score]').textContent=`Al primer intento: ${plugin.getMetrics().firstTryCorrect}`;}}
 function renderRound(next){if(next.status==='insufficient')return openConfiguration();result=next;q('[data-round]').textContent=`Ronda ${next.round} de ${next.total} · ${next.variantLabel}`;q('[data-operation]').textContent=`Operación: ${labels[next.operation]}`;q('[data-base]').textContent=next.baseWord;const policy=configurator.getPolicy();q('[data-instruction]').textContent=policy.explicitFeedback?`${next.instruction} Sigue los pasos de la ayuda.`:next.instruction;refs.helper.textContent=next.helperInstruction;refs.helper.classList.toggle('hidden',!policy.alwaysShowHelp);refs.help.classList.toggle('hidden',policy.alwaysShowHelp);refs.help.setAttribute('aria-expanded',String(policy.alwaysShowHelp));updateSessionProgress(refs.progress,refs.progress.firstElementChild,next.round,next.total);q('[data-revealed]').textContent='';refs.check.classList.remove('hidden');refs.next.classList.add('hidden');update(next);}
 function configureProfessional(){renderProfessionalControls(refs.professional,plugin,configurator.getPolicy(),{restart:()=>renderRound(plugin.restartRound()),skip:()=>{const skipped=plugin.skipRound();if(skipped.round>=skipped.total)finishSession();else renderRound(plugin.next());},help:()=>refs.helper.classList.toggle('hidden'),finish:()=>dialogs.finish.open(()=>{plugin.finishSession();finishSession();})});}
 function finishSession(){renderSummary();shell.show('manip-summary');}
 function renderSummary(){const m=plugin.getMetrics();q('[data-metrics]').innerHTML=renderCommonMetrics(m);q('[data-groups]').innerHTML=Object.entries(m.byOperation).filter(([,v])=>v.rounds).map(([key,v])=>`<div><strong>${labels[key]}</strong><br>${v.rounds} rondas · ${v.firstTryCorrect} al primer intento · ${v.incorrectAttempts} ${v.incorrectAttempts===1?'error':'errores'}</div>`).join('');q('[data-interaction]').textContent=`${m.totalMovements} movimientos · ${m.totalUndoUses} usos de Deshacer · ${m.totalResetUses} usos de Reiniciar · ${m.therapistRestarts} reinicios profesionales`;q('[data-results]').innerHTML=m.results.map(item=>`<li><span><strong>${item.baseWord}</strong> · ${labels[item.operation]}<br>${item.instruction}${item.status==='skipped'?'':`<br>Resultado: ${item.result}`}<br></span><span>${item.status==='skipped'?'Omitida':item.firstTry?'✓ Primer intento':'↻ Varios intentos'}</span></li>`).join('');}
 function destroy(){events?.abort();clearProfessionalControls(refs?.professional);host?.remove();host=refs=configurator=events=result=null;dragged=null;}
 return{activityId:MANIPULATE_SYLLABLES_ACTIVITY_ID,mount,openConfiguration,startSession,renderRound,finishSession,renderSummary,destroy};
}
