import { updateSessionProgress } from '../session/sessionProgress.js';
import { renderCommonMetrics } from '../session/sessionSummary.js';
import { clearProfessionalControls, renderProfessionalControls } from '../session/professionalControls.js';

export const ORDER_SYLLABLES_ACTIVITY_ID = 'order-syllables';

const template = `<section id="order-config" class="screen" aria-labelledby="order-config-title"><button class="back-link" data-runtime-home type="button">← Volver al inicio</button><p class="brand">LEXIA</p><h1 id="order-config-title" tabindex="-1">Configura Ordenar sílabas</h1><form data-config class="session-config"></form></section>
<section id="order-game" class="screen game" aria-labelledby="order-game-title"><header class="game-header"><div><p data-round>Ronda 1 de 5</p><p data-score>Al primer intento: 0</p></div><button data-exit class="secondary" type="button">Salir de la actividad</button></header><div data-progress class="progress" role="progressbar" aria-label="Progreso de la sesión"><span></span></div><div data-professional class="professional-bar hidden" aria-label="Controles profesionales"></div><div class="play-card"><p class="brand">ORDENAR SÍLABAS</p><h1 id="order-game-title" tabindex="-1">Forma la palabra</h1><p data-instruction></p><button data-help-toggle class="help-toggle" type="button" aria-expanded="false" aria-controls="order-helper">¿Cómo se hace?</button><div id="order-helper" data-helper class="manip-helper hidden"><p>Pulsa las sílabas en el orden en que las escuchas al decir la palabra.</p><p>Puedes usar Deshacer si quieres cambiar la última ficha.</p><p data-guidance class="hidden"></p></div><div data-pieces class="pieces" aria-label="Sílabas disponibles"></div><p class="zone-label">Tu respuesta</p><div data-answer class="answer" aria-label="Respuesta construida"></div><div data-edit class="edit-controls"><button data-undo class="secondary" type="button">↶ Deshacer</button><button data-clear class="secondary" type="button">Limpiar</button></div><p data-feedback class="feedback" aria-live="polite">Elige una sílaba para empezar.</p><p data-revealed class="revealed" aria-live="polite"></p><button data-check class="primary wide" type="button" disabled>Comprobar respuesta</button><button data-next class="primary wide hidden" type="button">Siguiente ronda</button><button data-empty-back class="secondary wide hidden" type="button">Volver a la configuración</button></div></section>
<section id="order-summary" class="screen" aria-labelledby="order-summary-title"><p class="brand">SESIÓN COMPLETADA</p><h1 id="order-summary-title" tabindex="-1">Resumen final</h1><div data-metrics class="metrics"></div><h2>Palabras trabajadas</h2><ul data-results class="results"></ul><div class="summary-actions"><button data-repeat class="primary" type="button">Repetir configuración</button><button class="secondary" data-runtime-home type="button">Volver al inicio</button></div></section>`;

export function createOrderSyllablesController({ plugin, root, shell, dialogs, createConfigurator }) {
  let host, refs, configurator, events, session, dragged;
  const q = selector => host.querySelector(selector);
  function mount() {
    if (host) return;
    host = document.createElement('div'); host.dataset.activityRoot = ORDER_SYLLABLES_ACTIVITY_ID; host.innerHTML = template; root.append(host);
    refs = { form:q('[data-config]'), pieces:q('[data-pieces]'), answer:q('[data-answer]'), feedback:q('[data-feedback]'), helper:q('[data-helper]'), guidance:q('[data-guidance]'), help:q('[data-help-toggle]'), revealed:q('[data-revealed]'), check:q('[data-check]'), next:q('[data-next]'), undo:q('[data-undo]'), clear:q('[data-clear]'), edit:q('[data-edit]'), empty:q('[data-empty-back]'), progress:q('[data-progress]'), professional:q('[data-professional]') };
    configurator = createConfigurator(refs.form, ORDER_SYLLABLES_ACTIVITY_ID); events = new AbortController(); const options = { signal: events.signal };
    refs.form.addEventListener('submit', event => { event.preventDefault(); startSession(); }, options);
    host.addEventListener('click', handleClick, options); refs.answer.addEventListener('dragover', event => event.preventDefault(), options); refs.answer.addEventListener('drop', handleDrop, options); host.addEventListener('dragstart', handleDragStart, options);
  }
  function handleClick(event) {
    if (event.target.closest('[data-runtime-home]')) { destroy(); shell.home(); return; }
    if (event.target.closest('[data-exit]')) { dialogs.exit.element.showModal(); return; }
    if (event.target.closest('[data-repeat], [data-empty-back]')) return openConfiguration();
    if (event.target.closest('[data-help-toggle]')) { const expanded = refs.help.getAttribute('aria-expanded') === 'true'; refs.help.setAttribute('aria-expanded', String(!expanded)); refs.helper.classList.toggle('hidden', expanded); return; }
    const piece = event.target.closest('[data-piece]');
    if (piece && refs.pieces.contains(piece)) return apply(plugin.submit({ type:'tap', pieceId:piece.dataset.piece }));
    if (piece && refs.answer.contains(piece)) { const index=Number(piece.dataset.answerIndex); if(session.round.variant==='intruder') return apply(plugin.submit({type:'remove-piece',pieceId:piece.dataset.piece})); if(session.selectedAnswerIndex==null){session.selectedAnswerIndex=index; renderAnswer(session.round.answer);}else{const fromIndex=session.selectedAnswerIndex;session.selectedAnswerIndex=null;apply(plugin.submit({type:'move',fromIndex,toIndex:index}));} return; }
    if (event.target.closest('[data-undo]')) apply(plugin.submit({type:'undo'}));
    if (event.target.closest('[data-clear]')) apply(plugin.submit({type:'clear'}));
    if (event.target.closest('[data-check]')) apply(plugin.submit({type:'validate'}));
    if (event.target.closest('[data-next]')) { if(session.current>=session.total) finishSession(); else {session.current+=1;renderRound(plugin.next());} }
  }
  function handleDragStart(event){const piece=event.target.closest('[data-piece]');if(piece)dragged={pieceId:piece.dataset.piece,fromIndex:piece.dataset.answerIndex==null?null:Number(piece.dataset.answerIndex)};}
  function handleDrop(event){event.preventDefault();if(!dragged)return;const target=event.target.closest('[data-answer-index]');const result=dragged.fromIndex==null?plugin.submit({type:'tap',pieceId:dragged.pieceId}):plugin.submit({type:'drop',fromIndex:dragged.fromIndex,toIndex:target?Number(target.dataset.answerIndex):session.round.answer.length-1});dragged=null;apply(result);}
  function openConfiguration(){ shell.show('order-config'); }
  function startSession(){const config=configurator.getConfig();session={config,total:config.rounds,current:1,round:null,selectedAnswerIndex:null};configureProfessional();shell.show('order-game');renderRound(plugin.start(config));}
  function renderRound(result){if(!result||result.status==='empty'||!Array.isArray(result.pieces)){refs.pieces.innerHTML='';renderAnswer([]);refs.feedback.textContent='No hay suficientes palabras disponibles para esta configuración';refs.feedback.className='feedback error';refs.check.classList.add('hidden');refs.next.classList.add('hidden');refs.edit.classList.add('hidden');refs.empty.classList.remove('hidden');return;}session.round=result;q('[data-round]').textContent=`Ronda ${session.current} de ${session.total} · ${result.variantLabel??'Ordenar la palabra'}`;q('[data-score]').textContent=`Al primer intento: ${plugin.getMetrics().firstTryCorrect}`;updateSessionProgress(refs.progress,refs.progress.firstElementChild,session.current,session.total);refs.pieces.innerHTML=result.pieces.map(piece=>`<button class="piece" type="button" draggable="true" data-piece="${piece.id}">${piece.text}</button>`).join('');const policy=configurator.getPolicy(),showHelp=policy.alwaysShowHelp;refs.helper.classList.toggle('hidden',!showHelp);refs.help.classList.toggle('hidden',policy.alwaysShowHelp);refs.help.setAttribute('aria-expanded',String(showHelp));refs.guidance.classList.add('hidden');q('[data-instruction]').textContent=result.instruction;q('#order-game-title').textContent=result.variantLabel??'Forma la palabra';renderAnswer(result.answer);refs.feedback.textContent='Elige una sílaba para empezar.';refs.feedback.className='feedback';refs.revealed.textContent='';refs.check.classList.remove('hidden');refs.next.classList.add('hidden');refs.edit.classList.remove('hidden');refs.empty.classList.add('hidden');updateControls(result);}
  function renderAnswer(answer){refs.answer.innerHTML=answer.length?answer.map((piece,index)=>`<button class="answer-piece${session.selectedAnswerIndex===index?' selected':''}" type="button" draggable="true" data-answer-index="${index}" data-piece="${piece.id}" aria-label="${piece.text}, posición ${index+1}">${piece.text}</button>`).join(''):'<span class="placeholder">Aquí aparecerá tu respuesta</span>';}
  function updateControls(result){const used=new Set(result.answer.map(piece=>piece.id));refs.pieces.querySelectorAll('[data-piece]').forEach(button=>{button.disabled=used.has(button.dataset.piece)||result.status==='correct';});refs.undo.disabled=!result.answer.length||result.status==='correct';refs.clear.disabled=!result.answer.length||result.status==='correct';refs.check.disabled=result.answer.length!==result.expectedLength||['correct','incorrect','locked'].includes(result.status);}
  function apply(result){session.round=result;renderAnswer(result.answer);updateControls(result);if(result.status==='incorrect'){refs.feedback.textContent=configurator.getPolicy().explicitFeedback?result.hint:'Revisa la consigna y prueba un cambio concreto.';refs.feedback.className='feedback error';if(configurator.getPolicy().explicitFeedback){refs.guidance.textContent=result.hint;refs.guidance.classList.remove('hidden');}}if(result.status==='correct'){refs.feedback.textContent='¡Muy bien! Has formado la palabra.';refs.feedback.className='feedback success';refs.revealed.textContent=result.word;refs.check.classList.add('hidden');refs.next.classList.remove('hidden');q('[data-score]').textContent=`Al primer intento: ${plugin.getMetrics().firstTryCorrect}`;}}
  function configureProfessional(){renderProfessionalControls(refs.professional,plugin,configurator.getPolicy(),{restart:()=>renderRound(plugin.restartRound()),skip:()=>{plugin.skipRound();if(session.current>=session.total)finishSession();else{session.current+=1;renderRound(plugin.next());}},help:()=>refs.helper.classList.toggle('hidden'),finish:()=>dialogs.finish.open(()=>{plugin.finishSession();finishSession();})});}
  function finishSession(){renderSummary();shell.show('order-summary');}
  function renderSummary(){const metrics=plugin.getMetrics();q('[data-metrics]').innerHTML=renderCommonMetrics(metrics);q('[data-results]').innerHTML=metrics.results.map(item=>`<li><strong>${item.word}</strong><span>${item.status==='skipped'?'Omitida':item.firstTry?'✓ Al primer intento':'↻ Necesitó varios intentos'}</span></li>`).join('');}
  function destroy(){events?.abort();clearProfessionalControls(refs?.professional);host?.remove();host=refs=configurator=events=session=null;dragged=null;}
  return {activityId:ORDER_SYLLABLES_ACTIVITY_ID,mount,openConfiguration,startSession,renderRound,finishSession,renderSummary,destroy};
}
